### ISSUE TITLE
Azure Services Research

### ISSUE THREAD

**Issue by Kzeezee** [Kzeezee/Ensemble#5]
Do research on various types of Azure services and come up with the specific service in Azure for our application.

We need:
Static web host
Web app host for front end and compute service for our Java Spring Boot backend
Authentication service for our web app
Normal file storage for storing videos/assets for web application
Hosting all our resources together like in Amazon VPC
~~Database~~ - Done using Azure Database for PostgreSQL
~~Infrastructure to support our game~~ - Azure Playfab but needs to see whether Playfab auth and normal Azure Auth can work together

Any other notable Azure services that can help or enhance our project may be included as well.

**Comment by GoochTrimmer** [comment]
Azure Services for Ensemble 

Azure App Services:
1.	Static Web Application Support
2.	User Authentication 
3.	Backend Java Support

Azure Storage:
1.	Main Storage Component

PostgresSQL:
1.	Main Database 

Azure PlayFab:
1.	Unity Support
2.	Player Authentication (OpenID Connect)
3.	Account Retrieval

Azure Media Services:
1.	Live audio and video encoding
2.	Compatible with Azure Storage

**Comment by Kzeezee** [comment]
Looks good!
